/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include <stdio.h>

typedef struct _uib_view1_control_context {
	/* add your variables here */

} uib_view1_control_context;

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */

char *my_getString(int nb)
{
	char *str = NULL;
	int i = 1;
	int j = 1;
	int k = 0;
	int x = nb;

	if (nb < 0)
		str[k++] = '-';

	while (x > 9)
	{
		x = x / 10;
		i = i * 10;
		j++;
	}
	str = malloc(k + j + 1);
	while (nb > 0)
	{
		str[k++] = (nb / i) + '0';
		nb = nb % i;
		i = i / 10;
	}
	str[k] = 0;
	return str;
}

void view1_button1_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info)
{
	Elm_Object_Item *selected = elm_list_selected_item_get(vc->list3);
	const char *sel = elm_object_item_data_get(selected);
	dlog_print(DLOG_DEBUG, "IOT", "Item selected : %s | Data : %s", elm_object_item_text_get(selected), sel);
	evas_object_hide(vc->list3);

	JsonObject *json = getDataByCityName(sel);
	if (json == NULL)
		return;

	JsonObject *main = json_object_get_object_member(json, "main");
	int temp = json_object_get_int_member(main, "temp");

	elm_object_text_set(vc->temperature, strcat(my_getString(temp - 273), "°C"));
	int pres = json_object_get_int_member(main, "pressure");
	elm_object_text_set(vc->pressure, strcat(my_getString(pres), "hPa"));
	int humi = json_object_get_int_member(main, "humidity");
	elm_object_text_set(vc->humidity, strcat(my_getString(humi), "%"));

	int visi = json_object_get_int_member(json, "visibility");
	elm_object_text_set(vc->visibility, strcat(my_getString(visi), "000m"));

	JsonObject *sys = json_object_get_object_member(json, "sys");
	int sunrise = json_object_get_int_member(sys, "sunrise");
	elm_object_text_set(vc->sunUp, my_getString(sunrise));
	int sunset = json_object_get_int_member(sys, "sunset");
	elm_object_text_set(vc->sunDown, my_getString(sunset));

}

/**
 * @brief The entry has been clicked (mouse press and release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view1_entry1_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info)
{
	if (strcmp(elm_object_text_get(vc->entry1), "Enter City's name") == 0)
	{
		elm_object_text_set(vc->entry1, "");
	}
}

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view1_geolocation_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {

}
/**
 * @brief The text within the entry was changed because of user interaction.
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		Elm_Entry_Change_Info *entry_change_info = (Elm_Entry_Change_Info *) event_info;
 *
 */
void view1_entry1_onchanged_user(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	citiesList_search(elm_object_text_get(vc->entry1), vc);
}

/**
 * @brief The entry has received focus.
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view1_entry1_onfocused(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	evas_object_show(vc->list3);
}

/**
 * @brief When the list item has received focus. (since 1.10)
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		Elm_Object_Item *list_item = (Elm_Object_Item *) event_info;
 *
 */
void view1_list3_onitem_focused(uib_view1_view_context *vc, Evas_Object *obj, void *event_info)
{
	Elm_Object_Item *selected = (Elm_Object_Item *)event_info;
	const char *sel = elm_object_item_data_get(selected);
	elm_object_text_set(vc->entry1, sel);
}
