/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include <stdio.h>

typedef struct _uib_view1_control_context {
	/* add your variables here */

} uib_view1_control_context;

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */

char *my_getString(int nb)
{
	char *str = NULL;
	int i = 1;
	int j = 1;
	int k = 0;
	int x = nb;

	if (nb < 0)
		str[k++] = '-';

	while (x > 9)
	{
		x = x / 10;
		i = i * 10;
		j++;
	}
	str = malloc(j + 1);
	while (nb > 0)
	{
		str[k++] = (nb / i) + '0';
		nb = nb % i;
		i = i / 10;
	}
	str[k] = 0;
	return str;
}

void view1_button1_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	char *name_city = NULL;

	name_city = strdup(elm_object_text_get(vc->entry1));
	if (name_city == NULL)
		return;

	JsonObject *json = getDataByCityName(name_city);

	JsonObject *main = json_object_get_object_member(json, "main");
	int temp = json_object_get_int_member(main, "temp");
	elm_object_text_set(vc->temperature, my_getString(temp));
	int pres = json_object_get_int_member(main, "pressure");
	elm_object_text_set(vc->pressure, my_getString(pres));
	int humi = json_object_get_int_member(main, "humidity");
	elm_object_text_set(vc->humidity, my_getString(humi));

	int visi = json_object_get_int_member(json, "visibility");
	elm_object_text_set(vc->visibility, my_getString(visi));

	JsonObject *sys = json_object_get_object_member(json, "sys");
	int sunrise = json_object_get_int_member(sys, "sunrise");
	elm_object_text_set(vc->sunUp, my_getString(sunrise));
	int sunset = json_object_get_int_member(sys, "sunset");
	elm_object_text_set(vc->sunDown, my_getString(sunset));

}

/**
 * @brief The entry has been clicked (mouse press and release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view1_entry1_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_object_text_set(vc->entry1, "");
}

